name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.24.3
        pip install torch==2.2.1 torchvision==0.17.1 --index-url https://download.pytorch.org/whl/cpu
        pip install pytest==7.3.1
        pip install matplotlib==3.8.3
    
    - name: Train model
      run: |
        python src/train.py
        
    - name: Run tests
      run: |
        pytest tests/

    - name: Archive model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          model_*.pth
          training_metrics.png
          augmented_samples/*.png
        retention-days: 90